apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: development
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
