apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: development
data:
  node_env: "" # production
  db_url: "" # mongo db atlas
  jwt_secret: "" # 777
  backend_url: "http://api-service.development"